- id: '1753114180411'
  alias: Wasserventil Automatik
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.wasserventil_automatik
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  conditions: []
  actions:
  - type: turn_on
    device_id: 2df578b732c01c4450bb9f113be7e714
    entity_id: 359b3d1a752509da08d4d8a3497f13c9
    domain: switch
  - delay: '{{ states(''input_number.wasserventil_laufzeit'') | multiply(60) | int
      }}'
  - type: turn_off
    device_id: 2df578b732c01c4450bb9f113be7e714
    entity_id: 359b3d1a752509da08d4d8a3497f13c9
    domain: switch
  mode: single
