# Loads default set of integrations. Do not remove.
default_config:


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notify.yaml

recorder:
  purge_keep_days: 1095
  db_url: !secret db_url
  exclude:
    entities:
    - sensor.last_boot
    - zone.home
    - binary_sensor.updater
    - http.logon
    - person.Bettina
    - person.Peter
    - person.Florian

homeassistant:
  packages: !include_dir_named packages

http:
  ip_ban_enabled: true
  login_attempts_threshold: 4
  use_x_forwarded_for: true
  trusted_proxies:
    - 11.0.0.0/16 # Docker Subnet
    - 192.168.178.0/24
    - 10.0.30.0/24
