# https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/manifest.json
homeassistant:
  name: Hülben
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 713
  unit_system: metric
  currency: EUR
  time_zone: Europe/Berlin
  country: DE
  internal_url: !secret internal_url
  external_url: !secret external_url
  temperature_unit: C
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named integrations
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
automation manual: !include_dir_merge_list automations
api:
config:
# cloud:
energy:
scene: !include scenes.yaml
history:
  exclude:
    entities:
    - sensor.last_boot
    - zone.home
    - binary_sensor.updater
    - http.logon
    - person.Bettina
    - person.Peter
    - person.Florian
http:
  ip_ban_enabled: true
  login_attempts_threshold: 4
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.setup: warning
    homeassistant.bootstrap: warning
    homeassistant.util.json: warning
    homeassistant.components.network.network: warning
    homeassistant.loader: warning
    homeassistant.helpers.restore_state: warning
    homeassistant.components.http: warning
    homeassistant.components.recorder: warning
    botocore.hooks: warning
    homeassistant.components.scene: warning
    homeassistant.components.sun: warning
    homeassistant.components.notify: warning
    homeassistant.components.websocket_api.http.connection: warning
    homeassistant.components.automation: warning
    homeassistant.helpers.event: warning
    # sungrow integration
    pymodbus.client: warning
    # sungrow integration
    homeassistant.components.modbus: warning
lovelace:
  mode: yaml
  resources:
    - url: /local/mini-graph-card-bundle.js?v=0.11.0
      type: module
    - url: /local/mushroom.js
      type: module
    - url: /local/apexcharts-card.js?v=2.0.4
      type: module
  dashboards:
    dashboard-01:
      title: PV-Anlage
      mode: yaml
      filename: dashboards/pv_dashboard.yaml
      icon: mdi:solar-power-variant
      show_in_sidebar: true
      require_admin: false
    dashboard-02:
      title: PV-Sungrow-default
      mode: yaml
      filename: dashboards/pv_sungrow_default.yaml
      icon: mdi:solar-power-variant
      show_in_sidebar: true
      require_admin: true
    dashboard-03:
      title: PV-Anlage-wip
      mode: yaml
      filename: dashboards/pv_dashboard_wip.yaml
      icon: mdi:solar-power-variant
      show_in_sidebar: true
      require_admin: true
    dashboard-04:
      title: Garten
      mode: yaml
      filename: dashboards/garden_dashboard.yaml
      icon: mdi:shovel
      show_in_sidebar: true
      require_admin: false
    # dashboard-haus:
    #   title: Haus
    #   filename: dashboards/haus_dashboard.yaml
    #   icon: mdi:home
    #   mode: yaml
    #   show_in_sidebar: true
    #   require_admin: false
    # dashboard-garten:
    #   title: Garten / Garage
    #   filename: dashboards/garten_dashboard.yaml
    #   icon: mdi:flower
    #   mode: yaml
    #   show_in_sidebar: true
    #   require_admin: false
media_source:
mobile_app:
my:
person:
recorder:
  purge_keep_days: 1095
  db_url: !secret db_url
script: !include scripts.yaml
command_line: !include command_line.yaml
sun:
system_health:
template: !include_dir_merge_list templates
timer:
zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 100
    icon: mdi:home%
